# do a trace (get more output to log), true or false
do_trace = true

# location of play command
playcmd = "/usr/bin/play"

# location of bluetoothctl command
blthctlcmd = "/usr/bin/bluetoothctl"

# file to play
playfile = "./data/pink-20.mp3"

# volume to play
playvolume = 0.03

# heart rate that indicates sleep
sleeplimit = 70

# MAC of heart rate sensor
heartMac = "F6:6E:44:7B:34:E5"

#MAC of headset
soundMac = "03:21:19:4E:3F:5F"

